name: test
description: A new Flutter project.
 
publish_to: 'none' 
 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  # Lnaguage
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  # Provider For Satae Managment
  provider: ^6.0.5
  # Function Programing Things
  dartz: ^0.10.1
  # Value Equatable
  equatable: ^2.0.5
  # Service Locator
  get_it: ^7.6.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.4
  # Local Storge
  shared_preferences: ^2.1.1
  # Icon Type SVG
  flutter_svg: ^2.0.0+1
  # Cache Network Image
  cached_network_image: ^3.2.3
  #Loading
  shimmer: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
